# Generated by Django 4.2.1 on 2023-10-09 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chop', '0002_rename_user_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='password',
        ),
    ]
