# Generated by Django 4.2.1 on 2023-10-26 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chop', '0006_order_product_shippingaddress_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='pas de description pour ce produit'),
            preserve_default=False,
        ),
    ]
