# Generated by Django 4.2.1 on 2023-10-29 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chop', '0007_remove_product_digital_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='zipcode',
            new_name='phone',
        ),
    ]
