# Generated by Django 4.2.1 on 2023-10-29 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chop', '0009_remove_shippingaddress_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSalesCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demand_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='global_sales_count',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='chop.globalsalescount'),
        ),
    ]
