# Generated by Django 4.2.1 on 2023-10-29 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chop', '0012_alter_shippingaddress_global_sales_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='global_sales_count',
        ),
    ]
