# Generated by Django 4.2.1 on 2023-10-29 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chop', '0013_remove_shippingaddress_global_sales_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='global_sales_count',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='chop.globalsalescount'),
        ),
    ]
