# Generated by Django 4.2.1 on 2023-10-29 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chop', '0015_remove_shippingaddress_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
    ]
