# Generated by Django 4.2.1 on 2023-10-29 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chop', '0017_order_complete_order_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
    ]
