# Generated by Django 4.2.1 on 2023-10-30 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chop', '0019_remove_shippingaddress_global_sales_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='date_added',
        ),
    ]
