# Generated by Django 4.2.1 on 2023-11-05 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chop', '0020_remove_orderitem_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
