# Generated by Django 4.2.1 on 2023-11-05 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chop', '0021_customer_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.TextField(default=0),
        ),
    ]
